name: Reset Quotas Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日午前0時UTC
  workflow_dispatch:  # 手動実行も可能

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Call reset quotas API
        run: |
          curl -X GET ${{ secrets.APP_URL }}/api/cron/reset-quotas \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -H "Origin: ${{ secrets.APP_URL }}" \
            --fail-with-body \
            --show-error \
            --silent
        continue-on-error: true

      - name: Log completion
        if: always()
        run: echo "Quota reset cron job completed at $(date)"
